#!/usr/bin/env bash
# This script transfers a file from our client to a server using SCP (Secure Copy Protocol).
#
# Check if the number of arguments provided is less than 4
if [ $# -lt 4 ]
then
# If there aren't enough arguments, display usage information
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  # If enough arguments are provided, execute SCP to transfer the file
  # -o StrictHostKeyChecking=no: Disable strict host key checking to prevent SCP from prompting for confirmation
  # -i "$4": Use the specified SSH private key for authentication
  # "$1": Path to the file to transfer
  # "$3@$2": Username and IP address of the server to transfer the file to
  # ~/ : Transfer the file to the home directory of the specified user on the server
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
