#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing Nginx, which should listen on port 80 and serve a page returning a "Hello World" string.

# Check if the script is run with root privileges
if [ "$(id -u)" -ne 0 ]; then
    echo "Please run this script with sudo or as root."
    exit 1
fi

# Update package lists and install Nginx
echo "Updating package lists and installing Nginx..."
apt-get update -qq && apt-get install -y nginx

# Check if Nginx installation was successful
if [ $? -ne 0 ]; then
    echo "Nginx installation failed. Exiting."
    exit 1
fi

# Start Nginx service if not already running
if systemctl is-active --quiet nginx; then
    echo "Nginx is already running."
else
    echo "Starting Nginx service..."
    systemctl start nginx
fi

# Allow Nginx through the firewall
echo "Allowing Nginx through the firewall..."
ufw allow 'Nginx HTTP'

# Set appropriate permissions and ownership for web directory
echo "Setting permissions and ownership for web directory..."
chown -R www-data:www-data /var/www/html
chmod -R 755 /var/www/html

# Backup default index file
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create a new index file with "Hello World!" content
echo "Creating index file with 'Hello World!' content..."
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Restart Nginx to apply changes
echo "Restarting Nginx..."
systemctl restart nginx

echo "Nginx configuration completed. ✅"
