#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing Nginx,
# which listens on port 80 and serves a page that returns a "Hello World" string.
# Additionally, it sets up a redirect from /redirect_me to a YouTube video.

echo -e "Updating and installing Nginx.\n"
# Update package lists and install Nginx silently
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Start Nginx service
sudo service nginx start

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership of website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create a new index with "Hello World!" content
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Set up /redirect_me to redirect to a YouTube video
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

echo -e "\nCompleted.\n"
