#!/usr/bin/env bash
# SSH client configuration
# Specify the location of the private key file to be used for authentication
    IdentityFile ~/.ssh/school

    # Specify the preferred method of authentication (public key)
    PreferredAuthentications publickey

    # Disable GSSAPI-based authentication
    GSSAPIAuthentication no

    #Enable credential delegation
    GSSAPIDelegateCredentials yes

    # Send specific environment variables to the SSH server
    SendEnv LANG LC_*
